### ISSUE TITLE
Add an option to avoid file renaming

### ISSUE THREAD

**Issue by marclaval** [PK1A/gulp-hsp-compiler#2]
Comment based on https://github.com/PK1A/hsp-hello-gulp/blob/master/src/index.html

To me, it feels weird to write `require('hello.hsp.js')` while the source file is in fact `hello.hsp`. As a developer, it means I have to write code based on what a tool will do.

**Comment by PK1A** [comment]
Fixed in `gulp-hashspace@0.0.2` via https://github.com/ariatemplates/gulp-hashspace/commit/f8cfe5744ab9110afde09b52f96ef497b16f6852
